import Head from 'next/head'
import Header from '@components/Header'
import Footer from '@components/Footer'
import LandingPage from './home';

import { getCookie } from 'cookies-next';

export async function getServerSideProps({ req, res }) {
  const user = getCookie('user', { req, res});
  if(user) {
    return {
      redirect: {
        permanent: false,
        destination: "/dashboard"
      }
    }
  } else {
    return {
      redirect: {
        permanent: false,
        destination: "/home"
      }
    }
  }
}
export default function Home() {

  return (
  
    <div className="container">
        <Head>
        <title>Blind Guru</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"></link>
      </Head>
      <main>
      </main>
      <Footer/>
    </div>
  )
}
